export default {
	FETCH_FILTER_DATA: "FETCH_FILTER_DATA",
	TOGGLE_FILTERS: "TOGGLE_FILTERS",
	FETCH_EMPLOYEES: "FETCH_EMPLOYEES",
	UPDATE_FILTERS: "UPDATE_FILTERS",
	TOGGLE_SELECT: "TOGGLE_SELECT",
	UPDATE_SELECTED_EMPS: "UPDATE_SELECTED_EMPS",
	DELETE_SELECTED_EMPS: "DELETE_SELECTED_EMPS",
	GET_EMPLOYEE_DETAILS: "GET_EMPLOYEE_DETAILS",
}